### ISSUE TITLE
Docker file for docker images

### ISSUE THREAD

**Issue by menacher** [minyk/docker-pinpoint#1]
Hi,
In your docker-compose.yml, you point to some docker images. For e.g.minyk/pinpoint-hbase:1.6.0, minyk/pinpoint-collector:1.6.0 and minyk/pinpoint-web:1.6.0. Could you please provide their corresponding docker files/other configuration files so that I can use to build them from scratch?

**Comment by minyk** [comment]
Hi @menacher 
I just build docker images with below command and retag them:
```
$ mvn clean package docker:build -DskipTests
```
Inside of Pinpoint's `pom.xml`, there is a plugin for docker build. so I just use them. If you want to know exactly what is happening, find maven docker plugin setting inside of `pom.xml`.

**Comment by menacher** [comment]
I saw that documentation in your README file right after I posted the issue...:) Thanks for your quick response. 
Also, I have noticed that the pinpoint web only shows the first request from your testapp. Any subsequent request(i had to call the same url many times) is only shown in the graph after a long time, have you see this behavior? Is it some configuration I need to update.

**Comment by minyk** [comment]
@menacher I barely know this apm, so I cannot say that's why. Maybe you use incognito mode of browser to try making a new connection from browser to test app. Try it :)

**Comment by menacher** [comment]
Thanks again for the quick response. I found the issue actually, profiler.sampling.rate=20 was set which meant it would only sample 5% of the requests.
